version: "3"
services:
  db:
    container_name: db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: passwd
      POSTGRES_DB: filesharing
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432" # DEVELOPMENT ONLY!!! REMOVE BEFORE RELEASING
  web:
    container_name: web
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/static:/data/static:ro
    depends_on:
      - backend
  backend:
    container_name: backend
    image: filesharing-backend:latest
    build:
      context: .
      dockerfile: backend/Dockerfile-backend
    depends_on:
      - db
    volumes:
      - ./storage:/data/app/storage

volumes:
  postgres_data: