FROM golang:latest

WORKDIR /data/app/backend

# Download dependencies
COPY backend/go.mod backend/go.sum ./
RUN go mod download

# Build the app
COPY backend/ ./
RUN go build -o main .

EXPOSE 8081

# Sleep for two seconds to give database time to start
CMD ["sh", "-c", "sleep 2 && ./main"]